name: Secret Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan_secrets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install TruffleHog
        run: |
          python -m pip install --upgrade pip
          pip install truffleHog

      - name: Scan for Secrets
        run: trufflehog filesystem --fail --json | tee trufflehog-report.json
